/**
 * APIFIX AI — Phase 21: Integration Platform, CLI & Enterprise Ecosystem Test Suite
 * 
 * Validates Source Control Providers (GitHub, GitLab, Bitbucket),
 * Enterprise SSO (OIDC/SAML/Google/Entra), SCIM 2.0 Provisioning,
 * CI/CD Platform Workflows, and Official APIFIX CLI.
 */

const { test, describe, before, after } = require('node:test');
const assert = require('node:assert/strict');
const http = require('http');
const util = require('util');
const { exec } = require('child_process');
const execAsync = util.promisify(exec);
const path = require('path');

const { app } = require('../src/server');
const apiKeyService = require('../src/services/apiKeyService');
const { getSourceControlProvider, GitHubProvider, GitLabProvider, BitbucketProvider } = require('../src/services/sourceControlProvider');
const { configureSso, getSsoConfig, processSsoCallback } = require('../src/services/identityProviderService');
const scimService = require('../src/services/scimService');
const ciCdService = require('../src/services/ciCdService');

let testServer = null;
let baseUrl = '';
let authApiKey = '';

async function api(method, endpointPath, { body, apiKey, headers = {} } = {}) {
  const reqHeaders = {
    'Content-Type': 'application/json',
    ...headers
  };
  if (apiKey) reqHeaders['Authorization'] = `Bearer ${apiKey}`;

  const res = await fetch(`${baseUrl}${endpointPath}`, {
    method,
    headers: reqHeaders,
    body: body ? JSON.stringify(body) : undefined
  });

  const contentType = res.headers.get('content-type') || '';
  let data = null;
  if (contentType.includes('json')) {
    data = await res.json().catch(() => null);
  } else {
    data = await res.text().catch(() => null);
  }

  return { status: res.status, headers: res.headers, data };
}

describe('Phase 21 — Enterprise Integrations, SCM, SSO, SCIM, CI/CD & CLI', () => {
  before(async () => {
    testServer = http.createServer(app);
    await new Promise((resolve) => testServer.listen(0, resolve));
    const port = testServer.address().port;
    baseUrl = `http://127.0.0.1:${port}`;

    const key = await apiKeyService.createApiKey({
      name: 'Integration Test Key',
      organizationId: 'org_enterprise_primary',
      workspaceId: 'ws_demo_primary',
      scopes: ['admin:all']
    });
    authApiKey = key.rawKey;
  });

  after(async () => {
    if (testServer) {
      await new Promise((resolve) => testServer.close(resolve));
    }
  });

  describe('1. Unified Source Control Provider Abstraction', () => {
    test('1.1 Should instantiate GitHub, GitLab, and Bitbucket providers', () => {
      const gh = getSourceControlProvider('github');
      const gl = getSourceControlProvider('gitlab');
      const bb = getSourceControlProvider('bitbucket');

      assert.equal(gh.name, 'GitHub');
      assert.equal(gl.name, 'GitLab');
      assert.equal(bb.name, 'Bitbucket');
    });

    test('1.2 Should create branch, commit, and Pull Request on GitHub provider', async () => {
      const gh = new GitHubProvider();
      const branch = await gh.createBranch('acme/api_gateway', 'main', 'apifix/fix_login_null');
      assert.equal(branch.name, 'apifix/fix_login_null');

      const commit = await gh.createCommit('acme/api_gateway', branch.name, 'fix: prevent null password crash', ['src/auth.js']);
      assert.ok(commit.sha);

      const pr = await gh.createPullRequest('acme/api_gateway', {
        title: 'APIFIX Automated Fix: Null Password Exception',
        body: 'Verified via sandbox tests.',
        head: branch.name,
        base: 'main'
      });
      assert.ok(pr.number);
      assert.ok(pr.url.includes('github.com'));
    });

    test('1.3 Should create Merge Request on GitLab provider', async () => {
      const gl = new GitLabProvider();
      const mr = await gl.createPullRequest('titan/payment_engine', {
        title: 'APIFIX Fix: Payment Null Pointer',
        body: 'Automated patch generated by APIFIX AI',
        head: 'apifix/fix_payment'
      });
      assert.ok(mr.number);
      assert.ok(mr.url.includes('gitlab.com'));
    });
  });

  describe('2. Enterprise Identity & SSO Integration', () => {
    test('2.1 Should configure OIDC SSO for organization', async () => {
      const config = await configureSso({
        organizationId: 'org_enterprise_primary',
        providerType: 'OIDC',
        issuerUrl: 'https://login.microsoftonline.com/tenant-id/v2.0',
        clientId: 'client_app_123',
        clientSecret: 'secret_456',
        roleMappings: {
          'APIFIX-ADMINS': 'ADMIN',
          'APIFIX-ENGINEERS': 'DEVELOPER'
        }
      });

      assert.equal(config.providerType, 'OIDC');
      assert.equal(config.enabled, true);
    });

    test('2.2 Should process SSO callback with JIT provisioning and role mapping', async () => {
      const result = await processSsoCallback({
        organizationId: 'org_enterprise_primary',
        claims: {
          sub: 'oidc_user_99',
          email: 'sarah.engineer@titan.com',
          name: 'Sarah Connor',
          groups: ['APIFIX-ENGINEERS']
        }
      });

      assert.ok(result.token);
      assert.equal(result.user.email, 'sarah.engineer@titan.com');
      assert.equal(result.user.role, 'DEVELOPER');
    });
  });

  describe('3. SCIM 2.0 Directory Provisioning (/scim/v2/*)', () => {
    test('3.1 Should provision user via SCIM POST /scim/v2/Users', async () => {
      const email = `john.dev_${Date.now()}@titan.com`;
      const res = await api('POST', '/scim/v2/Users', {
        apiKey: authApiKey,
        body: {
          schemas: ['urn:ietf:params:scim:schemas:core:2.0:User'],
          userName: email,
          name: { givenName: 'John', familyName: 'Doe' },
          emails: [{ value: email, primary: true }],
          active: true
        }
      });

      assert.equal(res.status, 201);
      assert.ok(res.data.id);
      assert.equal(res.data.userName, email);
      assert.equal(res.data.active, true);
    });

    test('3.2 Should list SCIM users via GET /scim/v2/Users', async () => {
      const res = await api('GET', '/scim/v2/Users', { apiKey: authApiKey });
      assert.equal(res.status, 200);
      assert.ok(Array.isArray(res.data.Resources));
      assert.ok(res.data.totalResults >= 1);
    });

    test('3.3 Should manage SCIM groups via /scim/v2/Groups', async () => {
      const res = await api('POST', '/scim/v2/Groups', {
        apiKey: authApiKey,
        body: {
          schemas: ['urn:ietf:params:scim:schemas:core:2.0:Group'],
          displayName: 'Platform SRE Core',
          members: []
        }
      });

      assert.equal(res.status, 201);
      assert.ok(res.data.id);
      assert.equal(res.data.displayName, 'Platform SRE Core');
    });
  });

  describe('4. CI/CD Integration & Workflow Generator', () => {
    test('4.1 Should generate GitHub Actions workflow YAML', () => {
      const wf = ciCdService.generateWorkflow('github', {
        projectId: 'proj_api_gateway',
        autoRepair: true
      });

      assert.equal(wf.filename, '.github/workflows/apifix-ci.yml');
      assert.ok(wf.content.includes('apifix verify --project "proj_api_gateway"'));
      assert.ok(wf.content.includes('apifix repair analyze'));
    });

    test('4.2 Should generate GitLab CI pipeline YAML', () => {
      const wf = ciCdService.generateWorkflow('gitlab', {
        projectId: 'proj_api_gateway'
      });
      assert.equal(wf.filename, '.gitlab-ci.yml');
      assert.ok(wf.content.includes('apifix verify'));
    });

    test('4.3 Should map deterministic exit codes', () => {
      assert.equal(ciCdService.getExitCode(null), 0);
      assert.equal(ciCdService.getExitCode(new Error('verification_failed: 2 regressions detected')), 1);
      assert.equal(ciCdService.getExitCode(new Error('unauthorized: invalid_api_key')), 2);
      assert.equal(ciCdService.getExitCode(new Error('rate_limit_exceeded')), 3);
      assert.equal(ciCdService.getExitCode(new Error('network_error: ECONNREFUSED')), 4);
    });
  });

  describe('5. Official APIFIX CLI Integration', () => {
    const cliPath = path.resolve(__dirname, '../../cli/bin/apifix.js');

    test('5.1 Should execute CLI --help and return exit code 0', async () => {
      const { stdout } = await execAsync(`node "${cliPath}" --help`);
      assert.ok(stdout.includes('APIFIX AI Enterprise CLI'));
      assert.ok(stdout.includes('COMMANDS:'));
      assert.ok(stdout.includes('EXIT CODES:'));
    });

    test('5.2 Should execute CLI --version and return exit code 0', async () => {
      const { stdout } = await execAsync(`node "${cliPath}" --version`);
      assert.ok(stdout.includes('APIFIX CLI v1.0.0'));
    });

    test('5.3 Should query status via CLI', async () => {
      const { stdout } = await execAsync(`node "${cliPath}" status --base-url "${baseUrl}" --json`);
      const parsed = JSON.parse(stdout);
      assert.ok(parsed.data || parsed.status);
    });

    test('5.4 Should list projects via CLI with --api-key and --json', async () => {
      const { stdout } = await execAsync(`node "${cliPath}" projects list --base-url "${baseUrl}" --api-key "${authApiKey}" --json`);
      const parsed = JSON.parse(stdout);
      assert.ok(parsed.data);
    });
  });
});
